- id: 1
  name: 主要
  rss_url: http://news.livedoor.com/topics/rss/top.xml
- id: 2
  name: 国内
  rss_url: http://news.livedoor.com/topics/rss/dom.xml
- id: 3
  name: 海外
  rss_url: http://news.livedoor.com/topics/rss/int.xml
- id: 4
  name: IT 経済
  rss_url: http://news.livedoor.com/topics/rss/eco.xml
- id: 5
  name: 芸能
  rss_url: http://news.livedoor.com/topics/rss/ent.xml
- id: 6
  name: スポーツ
  rss_url: http://news.livedoor.com/topics/rss/spo.xml
- id: 7
  name: 映画
  rss_url: http://news.livedoor.com/rss/summary/52.xml
- id: 8
  name: グルメ
  rss_url: http://news.livedoor.com/topics/rss/gourmet.xml
- id: 9
  name: 女子
  rss_url: http://news.livedoor.com/topics/rss/love.xml
- id: 10
  name: トレンド
  rss_url: http://news.livedoor.com/topics/rss/trend.xml
